package ba.sec.app.secApp.modelx;
// Generated Jul 3, 2017 10:18:42 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", catalog = "rest_db")
public class Authority implements java.io.Serializable {
	
	private static final long serialVersionUID = -5862247181512295107L;
	private AuthorityId id;
	private User user;

	public Authority() {
	}

	public Authority(AuthorityId id, User user) {
		this.id = id;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "email", column = @Column(name = "email", nullable = false)),
			@AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 80)) })
	public AuthorityId getId() {
		return this.id;
	}

	public void setId(AuthorityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
