package ba.sec.app.secApp.modelx;
// Generated Jul 3, 2017 10:18:42 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorityId generated by hbm2java
 */
@Embeddable
public class AuthorityId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String email;
	private String authority;

	public AuthorityId() {
	}

	public AuthorityId(String email, String authority) {
		this.email = email;
		this.authority = authority;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "authority", nullable = false, length = 80)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorityId))
			return false;
		AuthorityId castOther = (AuthorityId) other;

		return ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null && castOther.getEmail() != null
				&& this.getEmail().equals(castOther.getEmail())))
				&& ((this.getAuthority() == castOther.getAuthority()) || (this.getAuthority() != null
						&& castOther.getAuthority() != null && this.getAuthority().equals(castOther.getAuthority())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getAuthority() == null ? 0 : this.getAuthority().hashCode());
		return result;
	}

}
